### ISSUE TITLE
Главы и разделы отмечаются нежирным шрифтом

### ISSUE THREAD

**Issue by cpllbstr** [latex-g7-32/latex-g7-32#101]
Компиляция pdflatex-bibtex-pdflatex*2. Работает костыль через \textbf.

**Comment by LSinev** [comment]
Вы уверены, что это не так и задумано было? Можете процитировать конкретный пункт или пункты ГОСТ 7.32 в подтверждение этого тезиса (о жирности заголовков глав и разделов)?

**Comment by einhander** [comment]
@cpllbstr если хотите менять стиль заголовков, то используйте пакет titlesec. Применение textbf это уж точно костыль.
