### ISSUE TITLE
Требуется maintainer!

### ISSUE THREAD

**Issue by rominf** [latex-g7-32/latex-g7-32#103]
Прошёл примерно год с последнего коммита, и много issue не закрыто.
Судя по количеству звёздочек и суммарному количеству issue, этот проект пригодился многим, поэтому хочется, чтобы он активно поддерживался.
Большое спасибо всем, кто участвовал в разработке этого стиля! Он не был бы таким, каким он есть сейчас, без вас!
Понятно, что раз стиль рассчитан на дипломы и РПЗ, то вряд ли кто-нибудь будет пользоваться им всю жизнь (и, соответственно, поддерживать).
Поэтому было бы очень хорошо, если бы нашёлся человек, которому этот стиль нужен хотя бы в ближайшие года 2 и который бы мог его поддерживать! А там, может, найдётся и следующий maintainer.

Желающим просьба отписаться в комментарии к этому issue или мне в Телеграм (@rom_inf) или на почту (infroma@gmail.com).

**Comment by einhander** [comment]
Добрый день Роман, хорошо, что вы объявились. Некоторые вопросы не решаются без вас, например #43.
Что касается стиля, то я его использую на регулярной основе и бросать не собираюсь. Если будут другие люди которы смогут развивать этот стиль, то это было бы здорово, время это ресурс и его к сожалению не хватает.

**Comment by rominf** [comment]
@einhander, прошу прощения и сожалею, что не заметил тот issue. Выслал вам права Owner-а на организацию.
Если в будущем надо будет со мною связаться, прошу писать в Телеграм или на почту.

**Comment by rominf** [comment]
Стиль и шаблон живут и развиваются, я закрываю эту задачу.

Спасибо всем участникам!

PS: @einhander, я не нашёл ваших контактных данных. Напишите, пожалуйста, мне любым удобным для вас способом, см. контакты выше (но это не срочно).
