### ISSUE TITLE
Ссылки на веб-ресурсы

### ISSUE THREAD

**Issue by rominf** [latex-g7-32/latex-g7-32#13]

**Comment by fshp** [comment]
Ссылки работают, можно закрывать.

```
@online{Url00,
  title   = {Теория упругости},
  url     = {https://ru.wikipedia.org/wiki/Теория_упругости},
  urldate = {2017-05-25}
}
```

**Comment by ZyX-I** [comment]
Ссылки работают, но результат как‐то не похож на ГОСТ. Причём фактически всего, что я использовал.

**Comment by resolver0** [comment]
Попробуй вот так:
```
@online{GitLab,
    author = {[Электронный ресурс] {GitLab}},
    title = {официальный сайт},
    url = {https://about.gitlab.com/},
    urldate = {23.05.2018},
    language = "russian"
}
```

**Comment by kotoyama** [comment]
Дата обращения не работает.

**Comment by einhander** [comment]
Для bibtex шаблон библиографии gost https://ctan.org/texarchive/biblio/bibtex/contrib/gost

Для biblatex, biblatex-gost https://ctan.org/pkg/biblatex-gost

Думаю лучше использовать эти решения, тем более в примере РПЗ используется первый вариант. Второй более фичастый.
