### ISSUE TITLE
[Bug] стиль для бибтеха неадекватно обрабатывает нескольких авторов

### ISSUE THREAD

**Issue by kaedvann** [latex-g7-32/latex-g7-32#15]
Пример:

```
@TECHREPORT {,
    author      = {Welch G. and Bishop G.},
    title       = {An Introduction to the Kalman Filter},
    institution = {Department of Computer Science University of North Carolina at Chapel Hill},
    year        = {2006},
    number      = {95-041},
    month       = {Июль}
    pages       = {16}
}
```

Результат:
![image](https://cloud.githubusercontent.com/assets/5712222/7554396/6c4c1b64-f730-11e4-8534-37617fd77332.png)

**Comment by einhander** [comment]
Произведена замена используемого стиля для списка литературы на ugost2008 из стандартного пакета gost из TexLive.
Теперь должно обрабатывать нормально.
