### ISSUE TITLE
Доброго времени суток! А как у вас сделать титульный лист?

### ISSUE THREAD

**Issue by Felix-neko** [latex-g7-32/latex-g7-32#22]
Собственно, сабж.

^__^

**Comment by kaedvann** [comment]
Воспользоваться шаблоном, предоставленным тем, кто хочет от вас титульный лист. Если такого нет, можно попытаться на отдельно взятой странице вручную разогнать текст по нужным местам или просто подготовить его в любом другом редакторе и включать в документ как pdf.

**Comment by Felix-neko** [comment]
А что насчёт вот этого?

http://mydebianblog.blogspot.ru/2008/09/732-2001-latex.html

Не сможете ли вы как-то его интегрировать в ваш пакет?

**Comment by kaedvann** [comment]
У меня он в свое время не завелся. Кроме того, этот репозиторий является дальнейшим развитием тех стилей, которые содержатся по ссылке. Так что если у вас получится интегрировать эту штуку в то, что есть, и ничего не поломать - pull request'ы только приветствуются.

**Comment by einhander** [comment]
После вдумчивого чтения исходного кода, мне все удалось сделать Титульный лист, но моя ветка основана на наработках @imz  и боюсь на текущем master пока работать не будет. Я могу его залить, кому-нибудь нужно?

**Comment by Felix-neko** [comment]
Ещё как нужно!

P.S. Вот, я тут тоже наскоро сделал его на костылях, посмотрите и его тоже.

**Comment by Felix-neko** [comment]
https://github.com/Felix-neko/latex-g7-32

**Comment by einhander** [comment]
https://github.com/einhander/latex-g7-32
Вот мой вариант, в основном, дан образец что куда писать, ну и пара изменений в стиле чтобы оно не расползалось. Есть мнение, что по пакету нехватает документации, хотя бы по тому что уже есть и что меняться не будет.

**Comment by einhander** [comment]
Реализовано.
