### ISSUE TITLE
Некликабельные ссылки в оглавлении

### ISSUE THREAD

**Issue by dvarubla** [latex-g7-32/latex-g7-32#31]
При нажатии на ссылку в оглавлении вне нумерованной части (Заключение, Литература) перехода не происходит. По крайней мере в Evince и Adobe Reader 10. Если закомментировать строку `\setcounter{secnumdepth}{-1}` в G2-105.sty, то ссылки становятся кликабельными, но у них появляется номер.

**Comment by einhander** [comment]
Хочу уточнить, перехода нет или он ведет не туда?

**Comment by dvarubla** [comment]
@einhander  Перехода нет, как был на содержании, так и остался.

**Comment by einhander** [comment]
У меня они ведут на первую страницу.
Однозначно баг.

**Comment by einhander** [comment]
@dvarubla Я посмотрел возможные варианты обхода такого поведения, по хорошему надо переделать работу \frontmatter на подобии того как сделано в стандартном классе book. Но это по сути переработать весь стиль G2-105 от начала и до конца. Вряд ли я это смогу.
Второй вариант - не использовать \frontmatter и заменить в G7-32 команды создающие
введение, заключение на ненумеруемые, и добавить их в toc.
Например:



\newcommand\Introduction{%введение
 \chapter*{\CYRV\cyrv\cyre\cyrd\cyre\cyrn\cyri\cyre}%
\addcontentsline{toc}{chapter}{Введение}
}

Что выглядит немного как костыль, т.к. вложенные section будут нумерованы. Но где вы видели подразделы во введении и заключении?))

Это сделать не трудно, справитесь сами?

**Comment by LSinev** [comment]
http://www.itep.ru/science/dis/candidate_dissertation/detail.php?ID=1482
В некоторых диссертациях бывают подразделы во введении.

**Comment by einhander** [comment]
@LSinev Согласен это костыль, поэтому более правильно переделать работу \frontmatter.
Немного флейма )) ГОСТ 7.32 он про отчеты по НИР, для диссертаций все же наверное стоит использовать пакет disser. 
ИМХО нумерация раздела  начинающаяся с 0 вызывает некоторое недоумение.

В любом случае patches are welcome:)

**Comment by dvarubla** [comment]
@einhander Мне кажется, дело не в `\frontmatter`. У меня аналогичный пример не работает даже c article и sectsty. Я немного посмотрел исходники hyperref — там в названия секций дописывается ещё какой-то свой код, которому не нравится `\MakeUppercase`. Это можно исправить, например, добавив следующий код после подключения hyperref:
```
\makeatletter
\newif\ifGost@NeedUppercase
\let\Gost@old@sect\@sect
\def\@sect#1#2#3#4#5#6[#7]#8{%
	{\Gost@NeedUppercasefalse%
	\let\Gost@Uppercase\MakeUppercase%
	\renewcommand\MakeUppercase[1]{\Gost@NeedUppercasetrue ##1}%
	\Gost@old@sect{#1}{#2}{#3}{#4}{#5}{#6}[{#7}]{%
			\let\MakeUppercase\Gost@Uppercase %
			\ifGost@NeedUppercase\Gost@Uppercase{#8}\else #8\fi%
	}%
	}%
}
\makeatother
``` 
(Ну и потом сбросить переопределение в приложениях)

**Comment by einhander** [comment]
@dvarubla А \frontmatter  и не должен работать с article, он только с book работает.
В book кстати все нормально, но реализация \frontmatter сделана по другому.

**Comment by einhander** [comment]
Похоже это все же несовместимость \MakeUppercase и hyperref.

**Comment by dvarubla** [comment]
@einhander я не использовал `frontmatter` в примере с `article`. Там такой код:
```
\documentclass{article}
\usepackage{sectsty,textcase}
\setcounter{secnumdepth}{0}
\allsectionsfont{\MakeTextUppercase}
\usepackage[
bookmarks=true, colorlinks=true, unicode=true,
urlcolor=black,linkcolor=black, anchorcolor=black,
citecolor=black, menucolor=black, filecolor=black,
]{hyperref}
\begin{document}
\tableofcontents
\newpage
\section{Here's à la page}
\subsection{Straße}
\end{document}
```
Ссылки не кликабельные, по указанной мной причине. Вот пример с book: 
```
\documentclass{book}
\usepackage{sectsty,textcase}
\allsectionsfont{\uppercase}
\setcounter{secnumdepth}{0}
\usepackage[
bookmarks=true, colorlinks=true, unicode=true,
urlcolor=black,linkcolor=black, anchorcolor=black,
citecolor=black, menucolor=black, filecolor=black,
]{hyperref}
\begin{document}
\tableofcontents
\frontmatter
\chapter{Here's à la page}
\section{Straße}
\end{document}
```
Здесь немного по-другому, `chapter` — кликабельная, а `section` — нет. Причина, видимо, в том, что `chapter` в `book` не использует `@startsection` (и соответственно `@sect`), а использует свой макрос `@chapter`, который потом переопределяется в `hyperref`.

**Comment by einhander** [comment]
@dvarubla  Да к \frontmatter этот баг не имеет отношения, но тот способ отключения нумерации который использует этот пакет может в том числе приводить к описанному вами поведению (ссылку где -то потерял, но это не существенно).
У hypperref есть несовместимость с различными вариантами \MakeUppercase. Без \MakeUppercase все работает.
Вчера посмотрел различные варианты решения на so, ни одного рабочего не нашел.
Вы вроде решили эту проблему для себя, если есть желание подготовьте пулреквест.

**Comment by dvarubla** [comment]
@einhander А [мой код](https://github.com/latex-g7-32/latex-g7-32/issues/31#issuecomment-287713402) у вас работает? (его нужно поместить сразу после подключения hyperref в preamble.inc.tex)

**Comment by einhander** [comment]
Да только что проверил, работает.

**Comment by einhander** [comment]
@dvarubla Проверьте я добавил ваши правки в стиль. #34

**Comment by dvarubla** [comment]
@einhander Этого недостаточно, нужно ещё сбросить переопределение в приложениях и сделать пункт «Литература» кликабельным (сейчас он не работает). Попробую форкнуть ваш репозиторий и внести нужные правки.

**Comment by dvarubla** [comment]
Вот как-то [так](https://github.com/dvarubla/latex-g7-32/commits/Fix)

**Comment by einhander** [comment]
2dvarubla Добавил ваши исправления. А не хотите присоединится к разработке?

**Comment by dvarubla** [comment]
@einhander хотел бы. :) Только я не смогу часто коммитить.

**Comment by einhander** [comment]
@dvarubla Здесь никто не может часть коммитить)))
