### ISSUE TITLE
Заголовки не полужирного шрифта

### ISSUE THREAD

**Issue by klimentyev** [latex-g7-32/latex-g7-32#32]
При сборке проекта по умолчанию, ничего в нем не меняя после клонирования репозитория, отсутствует полужирный шрифт (bold) в заголовках разделов. Аналогично для слов из глоссария и списка сокращений. При этом далее по тексту полужирный шрифт есть.
Использую:
```
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016)
kpathsea version 6.2.2
```
Все необходимые пакеты установлены.
В чем может быть проблема?

**Comment by klimentyev** [comment]
Посмотрел внимательно ГОСТ. Был неправ. П. 6.1.2. Полужирный шрифт не применяется.
Меня смутило, что в примерах релизов от 28 Apr 2014 данные части были bold.

**Comment by einhander** [comment]
@klimentyev  Проверьте пожалуйста, у вас не работает только полужурный или еще и курсив.
Если курсив тоже не работает, то это ошибка, специфичная для xelatex.
Я использую pdflatex, и в нем нормально отображается полужирный шрифт.

**Comment by klimentyev** [comment]
@einhander Посмотрел внимательно, курсив есть, да вот только понял, что у меня в XeLaTex шрифты CMR... Я использую дистрибутив Calculate Linux, основанный на Gentoo, в нем отсутствует пакет `scalable-cyrfonts-tex`. Поэтому проверка `\IfFileExists{cyrtimes.sty}` не проходит.
Наверное, надо как-то по-другому подключать Times. Буду смотреть, как это сделано в шаблоне диссертации. В нем у меня XeLaTex подхватывает системный Times New Roman без проблем. Хочется добиться работоспособности этого шаблона, потому как нужен отчет по НИР, а от шаблона диссера придется слишком много лишнего "откусывать", чтобы использовать для этой цели :)

**Comment by einhander** [comment]
ИМХО проще шрифт указать стандартно для XeLaTex.
В пакете это сделано в файле G2-105.sty после подключения polyglossia.

**Comment by klimentyev** [comment]
@einhander Спасибо. Я пока что решил файл стиля не трогать. Считаю, что негоже чуть что лезть в них.
В преамбуле
```
\IfFileExists{cyrtimes.sty}
    {
        \usepackage{cyrtimespatched}
    }
    {
        % А если Times нету, то будет CM...
    }
```
заменил на (отсюда: https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/common/styles.tex)
```
\setmainlanguage[babelshorthands=true]{russian}  % Язык по-умолчанию русский с поддержкой приятных команд пакета babel
    \setotherlanguage{english}                       % Дополнительный язык = английский (в американской вариации по-умолчанию)
    \setmonofont{Courier New}
    \newfontfamily\cyrillicfonttt{Courier New}
    \defaultfontfeatures{Ligatures=TeX,Mapping=tex-text}
    \setmainfont{Times New Roman}
    \newfontfamily\cyrillicfont{Times New Roman}
    \setsansfont{Arial}
\newfontfamily\cyrillicfontsf{Arial}
```
Появились шрифты.

**Comment by LSinev** [comment]
Перспективней перейти на шрифты PT Astra: http://astralinux.com/fonts.html

**Comment by klimentyev** [comment]
@LSinev Спасибо за ссылку. Попробую. Я о них слышал, но никогда подробно не смотрел.

**Comment by einhander** [comment]
@LSinev Поддерживаю, можно включить шрифты репозиторий. Подготовите pull request?

**Comment by LSinev** [comment]
Не. Не готов пока пуллреквестить.

**Comment by einhander** [comment]
@LSinev Тогда, не сочтите за труд, сделать новый issue с вашим предложением по шрифтам.
В любом случае предложение хорошее и его обсуждение следует вести в отдельной задаче.
Вроде не сложно может и сам сделаю, когда время будет.
