### ISSUE TITLE
Переход на общедоступные отечественные шрифты PT Astra

### ISSUE THREAD

**Issue by LSinev** [latex-g7-32/latex-g7-32#33]
http://astralinux.com/fonts.html
> Требованиями органов государственного управления и иных учреждений предусмотрено применение зарубежного проприетарного шрифта Times New Roman при подготовке документов. Использование этого шрифта в операционных системах, отличных от MS Windows, требует заключения соответствующего лицензионного договора с правообладателем – компанией Monotype Imaging Inc. (США) и предусматривает денежные отчисления за каждый используемый экземпляр шрифта. Более того, в связи с санкционной политикой, проводимой в отношении Российской Федерации заключение такого лицензионного договора стало невозможным.
> 
> В целях обеспечения импортозамещения и перехода на использование отечественных информационных технологий разработчик операционных систем "Astra Linux" АО "НПО РусБИТех" и разработчик общенациональных шрифтов ООО НПП "ПараТайп" представляют общедоступные отечественные шрифты PT Astra Sans и PT Astra Serif, являющиеся полноценными метрическими аналогами зарубежного шрифта Times New Roman. Использование этих шрифтов вместо Times New Roman не приводит к искажению документов, а свободное распространение и кросс-платформенность в совокупности с замечательным дизайном делают их доступными и удобными для применения в любых операционных системах и офисных программных средствах.

![metrika1](https://cloud.githubusercontent.com/assets/12072891/24590778/fa60ffc6-17fb-11e7-818c-61acd4ec9895.png)
![metrika2](https://cloud.githubusercontent.com/assets/12072891/24590780/feaad304-17fb-11e7-9965-72fa1802e4cd.png)

http://www.paratype.ru/cinfo/news.asp?NewsId=3469
> Совместно с разработчиком операционных систем «Astra Linux» АО «НПО РусБИТех» ПараТайп представляет общедоступные шрифты PT Astra Sans и PT Astra Serif.
> Шрифты разработаны на основе Pt Sans и PT Serif, модифицированных таким образом, чтобы они подходили под стандарты оформления документов, эталоном ёмкости для которых является Times New Roman. Каждая из гарнитур представлена четырьмя базовыми начертаниями с широкой языковой поддержкой. Помимо стандартного набора знаков для работы с языками Западной и Восточной Европы, а также комплекта стандартной кириллицы, шрифты содержат знаки всех алфавитов государственных титульных языков Российской Федерации. Сформированные в рамках кроссплатформенного формата OT-TTF, шрифты дополнительно оптимизированы для экранов различного разрешения.
> PT Astra Sans, PT Astra Serif спроектированы дизайнерами Александрой Корольковой и Изабеллой Чаевой и подготовлены к выпуску компанией ПараТайп в 2016 году.
> [Скачать PT Astra Sans](http://www.paratype.ru/uni/public/PTAstraSans.zip) 
> [Скачать PT Astra Serif](http://www.paratype.ru/uni/public/PTAstraSerif.zip)
> С лицензией вы можете ознакомится, пройдя по следующей ссылке: [http://astralinux.ru/ofl.html](http://astralinux.ru/ofl.html)

**Comment by LSinev** [comment]
Подключить для xelatex или lualatex возможно по аналогии с описанным в https://github.com/latex-g7-32/latex-g7-32/issues/32#issuecomment-291010611

**Comment by klimentyev** [comment]
У меня так и не получилось подключить их.
! Package polyglossia Error:
The current roman font does not contain the Cyrillic script!
Please define \cyrillicfont with \newfontfamily.
Сколько бы ни переопределял, все равно ошибка. Документ собирается, но не все страницы.

**Comment by LSinev** [comment]
Делать надо кодом по аналогии с (и в ошибке пишут то же самое):
```tex
    \usepackage{polyglossia}                        % Поддержка многоязычности (fontspec подгружается автоматически)
    \setmainlanguage[babelshorthands=true]{russian} % Язык по-умолчанию русский с поддержкой приятных команд пакета babel
    \setotherlanguage{english}                      % Дополнительный язык = английский (в американской вариации по-умолчанию)
    \setmonofont{Courier New} % моноширинный шрифт
    \newfontfamily\cyrillicfonttt{Courier New}[Script = Cyrillic] % моноширинный шрифт для кириллицы
    \defaultfontfeatures{Ligatures=TeX} % стандартные лигатуры TeX, замены нескольких дефисов на тире и т. п. Настройки моноширинного шрифта должны идти до этой строки, чтобы при врезках кода программ в коде не применялись лигатуры и замены дефисов
    \setmainfont{Arial} % Основной шрифт
    \newfontfamily\cyrillicfont{Times New Roman}[Script = Cyrillic] % Основной шрифт для кириллицы
    \setsansfont{Times New Roman} % Шрифт без засечек
    \newfontfamily\cyrillicfontsf{Arial}[Script = Cyrillic] % Шрифт без засечек для кириллицы
    \usepackage{unicode-math} %\setmathfont
    \setmathfont[Scale=MatchLowercase]{Asana Math}
```
А если шрифты не находит, то кэш шрифтов обновляют командами из командной сроки:
```
fc-cache -f -v
luaotfload-tool -u -f
```

**Comment by klimentyev** [comment]
@LSinev Спасибо.
Шрифты он у меня и так видел. Чтобы не ставить шрифты в систему, я использую такую конструкцию:
```
  \setmainfont[ExternalLocation,
            Path = {../fonts/},
            Extension = {.ttf},
            UprightFont = {*-Regular},
            BoldFont = {*-Bold},
            ItalicFont = {*-Italic},
            BoldItalicFont = {*-BoldItalic}]{PTAstraSerif}
```
Шрифты положены в созданный каталог /fonts в проекте. В более простых шаблонах никаких проблем не было: подключал как Peterburg, так и литературную гарнитуры. Никаких ошибок.
Здесь же стоит задать \newfontfamily\ ...,получается пустой документ на 18 страниц (нет списков сокращений, определений и литературы). Если же сначала собирать проект, без подключенных PTAstraSerif, то с CM он генерируется отлично, затем я вставляю приведенный выше код в G2-105.sty и собираю еще раз через make. Собирается долго, потому что постоянно выводит ошибки, но в итоге полный документ со шрифтами PTAstraSerif. Я этого не могу понять. Получается, что TeXLive их видит, но как-то неправильно применяет...

**Comment by LSinev** [comment]
> `Path = {../fonts/},`

С работой с конструкциями внутри  `Path` недавно в `fontspec` был баг.

**Comment by LSinev** [comment]
> Чтобы не ставить шрифты в систему

При такой записи возможно стоит задавать шрифт дублируя его определение:
```tex
    \ifwindows
        \setmonofont{cour}[                     % Courier New
            Script = Latin,
            Path = c:/windows/fonts/,
            Extension = .ttf,
            UprightFont = *,
            BoldFont = *bd,
            ItalicFont = *i,
            BoldItalicFont = *bi]
        \newfontfamily\cyrillicfonttt{cour}[    % Courier New
            Script = Cyrillic,
            Path = c:/windows/fonts/,
            Extension = .ttf,
            UprightFont = *,
            BoldFont = *bd,
            ItalicFont = *i,
            BoldItalicFont = *bi]
    \else
        \setmonofont{Courier New}
        \newfontfamily\cyrillicfonttt{Courier New}[Script = Cyrillic]
    \fi
```

**Comment by klimentyev** [comment]
@LSinev Спасибо большущее!
Уже поставил, как вы советовали, через:
```
 fc-cache -f -v
 luaotfload-tool -u -f
```
Всё работает.

**Comment by klimentyev** [comment]
@LSinev Сделал подключение шрифтов: #51 . Только вот знаний для fallback на cmu в случае отсутствия необходимых шрифтов у меня не хватает.

**Comment by LSinev** [comment]
Достаточно [чужой код подсмотреть](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/common/styles.tex#L17) и задать имя шрифта через команду (`\newcommand`) по условию. Или весь блок кода сделать зависимым от условия.

И наверняка что-то есть в ответах на [tex.stackexchange.com](http://tex.stackexchange.com/).
