### ISSUE TITLE
Поддержка пакета nomencl

### ISSUE THREAD

**Issue by ZyX-I** [latex-g7-32/latex-g7-32#39]
В текущем коде аббревиатуры и определения находятся в отдельных файлах 10-defines и 11-abbrev, и подписаны «Абривиатуры вручную, зачем?» в rpz.tex (кстати, в комментарии две ошибки в одном слове). Есть возможность заменить эти два файла на пакет nomencl, для чего нужно:

1. Заменить два `\include` в rpz.tex на `\printnomenclature`.
2. Добавить в preamble.inc.tex

    ```latex
    % Сокращения
    \usepackage{nomencl}

    \renewcommand\nomname{}
    \renewcommand\nomgroup[1]{%
        \ifx#1A%
            \Abbreviations%
        \else%
            \Defines%
        \fi%
    }
    \renewcommand\nomlabel[1]{#1~---}
    \renewcommand\thenomenclature{%
        \list{}{%
            \let\makelabel\nomlabel%
        }%
    }

    \makenomenclature
    ```
3. Помимо bibtex также вызывать makeindex (в #38 это есть, но закомментировано).
4. Для создания аббревиатуры/определения использовать

    ```latex
    \nomenclature[A]{ABBREV}{expansion}
    \nomenclature[D]{Item}{definition}
    ```

Вопрос только в том, что эти `\renewcommand` вообще‐то хорошо бы отправить в какой‐нибудь .sty файл. Но если они появятся до `\usepackage{nomencl}`, то они будут переписаны пакетом nomencl.

Если что, в моём дипломе это генерирует две ожидаемые страницы:

![обозначения и сокращения и глоссарий](http://img-fotki.yandex.ru/get/218579/9151298.7/0_c3f24_71c1c6d0_orig.png)

Замечу, что чтобы поменять местами страницы придётся переделывать все вызовы `\nomenclature` (точнее, дополнительные аргументы A и D), а также второй аргумент `\ifx`. Думаю, имеет смысл создать команды `\Abbrev` и `\Define` в macros.inc.tex, а `A` и `D` спрятать под макросы `\AbbrevPrefix` и `\DefinePrefix` соответственно.

**Comment by ZyX-I** [comment]
Спрятал под макросы здесь: https://bitbucket.org/zyx-mephi/dip/changeset/30bc9fb3a7a1b9b9470cc73f12a8baf1ab2e02d3.

**Comment by einhander** [comment]
@ZyX-I Идея очень хорошая. Сам использую \printnomenclature.  Все это можно впихнуть в файл G7-32.sty  и добавить в make необходимые вызовы. Могу сделать я или хотите сами?

**Comment by dvarubla** [comment]
@einhander @ZyX-I Судя по [ГОСТ](ru.wikisource.org/wiki/ГОСТ_7.32—2001), заголовки должны быть прописными буквами, вместо «Глоссарий», должно быть «ОПРЕДЕЛЕНИЯ» и вроде сначала должны быть определения, потом обозначения.

**Comment by einhander** [comment]
@dvarubla Спасибо! Не углядел. Более того: 
5.6 **Определения**  
5.6.1 Структурный элемент «Определения» содержит определения, необходимые для уточнения или установления терминов, используемых в НИР.  
5.6.2 Перечень определений начинают со слов: «В настоящем отчете 0 НИР применяют следующие термины с соответствующими определениями».  
5.7 **Обозначения и сокращения**  
5.7.1 Структурный элемент «Обозначения и сокращения» содержит перечень обозначений и сокращений, применяемых в данном отчете 0 НИР.  
5.7.2 Запись обозначений и сокращений проводят в порядке приведения их в тексте отчета с необходимой расшифровкой и пояснениями.  
5.7.3 Допускается определения, обозначения и сокращения приводить в одном структурном элементе «**Определения, обозначения и сокращения**».

Из-за последнего пункта надо как-то обрабатывать изменение названия.

**Comment by ZyX-I** [comment]
Идея очень хорошая. Сам использую \printnomenclature. Все это можно впихнуть в файл G7-32.sty и добавить в make необходимые вызовы. Могу сделать я или хотите сами?> 

Я не уверен, что понял, что вы хотите запихнуть в G7-32.sty. Макросы настройки nomencl туда не запихиваются. Или моих знаний на это не хватает. Могу только предположить, что туда можно засунуть `\usepackage`, но без `\makenomenclature`: я `\usepackage` туда писать не хотел.

> Из-за последнего пункта надо как-то обрабатывать изменение названия.

Там «допускается», можно не обрабатывать, а делать два раздела как и сейчас. 5.6.2 можно запихнуть так же в `\Definitions`. А вот как обрабатывать 5.7.2 с nomencl я не знаю, разве что запихать в макрос `\Abbrev` префикс `printf("%s-%04u-%05u", \AbbrevPrefix, \thepage, {line number in tex file})`: printf() на нужном уровне вроде прост: берём `\ifnum` и пишем длинный некрасивый макрос, добавляющий 4..0 нулей; для `{line number in tex file}` есть https://tex.stackexchange.com/questions/81789/get-current-source-line-number, хотя я не проверял, номер какой строки он подставит (т.е. номер строки из rpz.tex, подключённого туда TeX файла или же номер строки из macros.inc.tex).

**Comment by einhander** [comment]
@ZyX-I  Закинул ваши предложения  в на скорую руку sty, работает. Чуть позже выложу результат.

**Comment by einhander** [comment]
Залил мою версию автоматических сокращений, реализовал 5.7.2. но 5.7.3 не стал делать.
@ZyX-I @dvarubla проверьте как работает у вас.

**Comment by einhander** [comment]
Ууупс, make скрипты не сделал, @ZyX-I  не хотите присоединится к разработке?
