### ISSUE TITLE
Не работает кириллица в формулах в PdfLaTeX

### ISSUE THREAD

**Issue by dvarubla** [latex-g7-32/latex-g7-32#54]
При использовании PdfLaTeX в файле G2-105.sty подключается пакет mathtext c комментарием `%русские буквы в формулах`. Этот пакет на самом деле перехватывает определение новых символов (вроде `\cyrt`), делая их совместимыми с math mode, и также перехватывает смену кодировки. Поэтому он [должен подключаться](http://tex.anabar.ru/TeX/doc/doc/tex_faq.txt) _до_ fontenc, inputnenc и babel. Более того, пакет hyperref переопределяет эти же символы, и где-то внутри себя меняет кодировку. Неудивительно, что кириллица в формулах не работает и к тому же выдаются предупреждения вроде «Font shape `PD1/cmr/m/n' undefined»

У меня есть идеи, как это исправить: запоминать переопределённые символы, убирать перехватывание смены кодировки сразу перед hyperref и потом возвращать. Можно ещё адаптировать ответ с [tex.stackexchange](https://tex.stackexchange.com/a/14687)

**Comment by einhander** [comment]
@dvarubla я к сожалению занят по горло. Если чувствуете в себе силы исправить ситуацию - действуйте.

**Comment by LSinev** [comment]
На мой взгляд, это вообще стоит выпилить из стиля. Пусть пользователь сам разбирается в своем конечном *.tex, нужна ли ему кириллица в формулах, и подключает, как ему хочется (всякие советы можно описать в wiki репозитория или в tex-примере реализации. А стиль, согласно названию, пусть занимается удовлетворением прописанных требований ГОСТ 2.105.

**Comment by dvarubla** [comment]
@LSinev мне нравится эта идея, но, как я написал выше, пакет mathtext должен подключаться до определённых пакетов, которые используются в стиле. То есть пользователю придётся править стиль. Это не очень хорошо.

**Comment by LSinev** [comment]
И их тоже не подключать. Скорее всего, их применения можно избежать, если не пытаться удовлетворять стилем разные хотелки, не требуемые по ГОСТ 2.105. Мало того, можно глянуть код пакета `pdfx` на то, как там делают, чтобы подключать что-то вообще до загрузки всего.
Если наследовать стиль (или переделать под класс, который тоже наследовать) от класса `memoir`, то ещё меньше кода и сложностей с подключением сторонних пакетов потребуется (многое уже решено `memoir`).

**Comment by dvarubla** [comment]
@LSinev вообще-то эти пакеты нужны для поддержки русского языка и кодировок в PdfLaTeX, поэтому без них не обойтись. В принципе, можно использовать `\def` до `\documentclass` и потом вставлять этот макрос куда необходимо, но это тоже, по-моему, не очень. При использовании memoir потребуется изучение этого пакета, значительное изменение стиля и ещё скорее всего придётся разбираться с его недостатками. Да и конфликтов между пакетами в стиле вроде бы немного.

**Comment by LSinev** [comment]
Русский язык и кодировки (да и большинство языков, кроме английского) по сложившейся практике работы с разными стилями (`article`, `report`, `book`, `memoir` и т. п.) вписывают в конечный tex, а не в используемый стиль или класс.
> При использовании memoir потребуется изучение этого пакета
Это полезно. Попробуйте, дайте этому классу шанс, вероятно, он не разочарует.

**Comment by einhander** [comment]
Пакет `mathtext` будет выкинут. См. #82
