### ISSUE TITLE
Ошибка с CMake при изменении исходников

### ISSUE THREAD

**Issue by dvarubla** [latex-g7-32/latex-g7-32#55]
Изменения исходных файлов из каталога src не отражаются в PDF файле. Подозреваю, это из-за того, что нет `DEPENDS` в командах перемещения или конвертирования этих файлов. Ещё странно, что компилятор LaTeX запускается, даже если вообще ни один файл не изменён.

**Comment by ZyX-I** [comment]
Компилятор файла и должен запускаться всегда, смысла городить огород с тем, чтобы он этого не делал я не видел. При изменении списка исходников нужно запустить `cmake ..`, в README это указано. При изменении самих файлов, а не списка всё в порядке.

**Comment by ZyX-I** [comment]
Хотя вы правы, почему‐то DEPENDS именно для src нет. Я просто их не использую, поэтому не заметил.
