### ISSUE TITLE
Центровка заголовка приложений

### ISSUE THREAD

**Issue by prodoelmit** [latex-g7-32/latex-g7-32#56]
Приветствую! Есть ли какая-то адекватная возможность центрировать заголовки в приложениях согласно пункту 6.14.3 ГОСТа? Пока смог навелосипедить только нечто с переопределением `\@startsection`, но получается как-то совсем не элегантно.

**Comment by dvarubla** [comment]
@prodoelmit в стиле никак не переопределяется `\@startsection`, поэтому будет работать что-то вроде такого: `\chapter[Картинки]{\\Картинки}`.

**Comment by einhander** [comment]
Сделано. Если будут вопросы открывайте заново.
