### ISSUE TITLE
Длинные тире слишком тонкие: их не видно в Adobe Reader

### ISSUE THREAD

**Issue by Felix-neko** [latex-g7-32/latex-g7-32#59]
Есть у меня документ, содержащий длинные тире.

Я компилирую его с помощью MikTeX под Windows.

Когда я открываю PDFку с помощью Adobe Reader, то длинные тире в документе оказываются столь тонкими, что на некоторых размерах (например, 100%) вообще не видны.

Как бы это забороть?

Пример прикладываю:

```
% Исходная версия шаблона --- 
% https://www.writelatex.com/coursera/latex/5.2.1

% Формат ГОСТ 7.32-2001, скачать тут: https://github.com/rominf/latex-g7-32
% поправлен <USERNAME> 2015-10-31, чтобы лучше
% соответствовать ГОСТ 7.32-2001 ред. 2009 года.pdf
\documentclass[report,utf8,usehyperref]{G7-32}

%\documentclass[12pt,twoside,a4paper]{article}


\usepackage[utf8x]{inputenc} %% ваша любимая кодировка здесь

\usepackage[english,russian]{babel} %% это необходимо для включения переносов
\usepackage{cyrtimespatched}


\begin{document} % конец преамбулы, начало документа
	
	(ВОТ ТУТ ДЛИННЫЕ ТИРЕ ВИДНЫ ТОЛЬКО В 125 \%, а на 100 \% уже не видны):
	\begin{itemize}
		\item bla:
		\item bla;
		\item blablabla;
		\item blablabla;
		\item няшки;
		\item показание примера упадка и падения нравов.
	\end{itemize}
	
	
	А --- Б.
		
\end{document}


```
Скриншот -- тут: http://imgur.com/a/fFDzK

**Comment by LSinev** [comment]
http://dxdy.ru/topic93210.html
https://tex.stackexchange.com/a/9357/79756
http://ru-tex.livejournal.com/185571.html
https://debianforum.ru/index.php?topic=815.msg17931#msg17931
https://www.linux.org.ru/forum/general/7492693

**Comment by dvarubla** [comment]
@Felix-neko быстрое решение: не использовать CM шрифт. На вашем скриншоте, несмотря на `\usepackage{cyrtimespatched}` используется именно он.

**Comment by Felix-neko** [comment]
@dvarubla , но на других-то стилевиках даже с CM-шрифтом всё нормально работает же?

А если я отключу CM, то у меня будут уродливые растровые шрифты же?

**Comment by dvarubla** [comment]
@Felix-neko я же написал: быстрое решение, во-первых. Во-вторых, я так понимаю, это связано с размером шрифта 14pt. В `\documentclass[a4paper,14pt]{extarticle}`. будет тот же баг. Сейчас пытаюсь разобраться дальше. Вообще, странно, как вы называете шрифт Times.

**Comment by Felix-neko** [comment]
@dvarubla , мы будем молиться за вас!

^_^

**Comment by dvarubla** [comment]
@Felix-neko увы, это не помогло. Вся проблема в этой строчке: `\@setfontsize\normalsize\@xivpt{17}`. Если указывать размер шрифта больше `13pt` (а `\@xivpt = 14.4`), то Acrobat начинает убирать тире.  

В принципе, тире можно переопределить. Но только не `---`, а `"---` (из babel). Либо рисовать этот символ самому, с помощью `\rule`, либо сделать его полужирным. Пример:

```latex
\documentclass[report,utf8]{G7-32}
\usepackage[utf8x]{inputenc}
\usepackage[russian]{babel}

%Раскомментировать одно из двух
%\def\testdash{\def\cyrdash{\rule[0.6ex]{.8em}{0.3pt}}}
%\def\testdash{\let\oldcyrdash\cyrdash\def\cyrdash{\textbf{\oldcyrdash}}}

\begin{document}
	
	А "--- Б А "--- Б

	А "--- Б \testdash А "--- Б
\end{document}
```

**Comment by Felix-neko** [comment]
Там главная проблема -- что делать с enumerate'ами и рисунками. А также прочими местами, куда тире вставляется именно --- (кажется).

**Comment by dvarubla** [comment]
@Felix-neko не могли бы вы проверить: у вас больше нигде тире не пропадают?

**Comment by Felix-neko** [comment]
А как мне склонировать pull request? Сможете написать, что нужно вбить в консоль, чтобы это сделать?

**Comment by ZyX-I** [comment]
У меня под это дело есть alias: `fpr = "!sh -c 'nr=\"$1\" ; shift ; git fetch upstream refs/pull/$nr/head:pr-$nr \"$@\"' -"`: `git fpr 60` создаст локально ветку `pr-60`, при условии что этот репозиторий сохранён как `upstream`, а не `origin`.

**Comment by ZyX-I** [comment]
Вообще можно просто запросить «ветку» `refs/pull/60/head` любым способом. Или напрямую брать из репозитория автора, имя ветки в PR написано.

**Comment by Felix-neko** [comment]
Во, я банально склонировал веточку у самого @dvarubla. Вроде теперь работает!

**Comment by Felix-neko** [comment]
UPD: на подписях к картинкам тире тоже теперь видно. Нраица!

**Comment by Felix-neko** [comment]
*офтопик*

Кстати, товарищи @dvarubla и @ZyX-I .

А не сможете ли вы отписать мне на почту ( felix-neko@list.ru )? Мы в своё время делали форк этого пакета, чтобы он с ГОСТом совпадал, но у нас уже точно не хватит сил, чтобы честно его слить с основной веткой. Если кто-нибудь из вас сможет это проделать, то будет архикруто. Ну и я смогу помочь чем смогу...

**Comment by dvarubla** [comment]
@Felix-neko лучше вместо `\def\testdash{\let\oldcyrdash\cyrdash\def\cyrdash{\textbf{\oldcyrdash}}}` и `\testdash` написать `\MakeDashesBold`, как это сделано в `preamble.inc.tex`. Насчёт вашего форка — к сожалению, у меня пока слишком мало времени, чтобы его интегрировать в текущий код. Возможно, @ZyX-I сможет это сделать. Ну или позже. Вообще, почему бы его не выложить на github? И что там реализовано, чего нет здесь?

**Comment by LSinev** [comment]
В тему возни с тире могут быть полезны отдельные элементы из статьи и комментариев: https://habrahabr.ru/post/310344/

**Comment by dvarubla** [comment]
@LSinev надеюсь, с тире уже всё. Вообще в статье вроде бы другие (меньшие) отступы, чем здесь и используется юникодное тире, которое тоже пропадает.
