### ISSUE TITLE
Отсутствуют коментарии на русском при использовании скрипта latexmkmod

### ISSUE THREAD

**Issue by einhander** [latex-g7-32/latex-g7-32#68]
Запуск через `/build.sh -bd mybuilddir`
Почему-то не отображаются комментарии на русском в листинге2. При сборке через cmake отображаются.

Лог:
https://gist.github.com/einhander/cabc07e7e1cae31fba261a22da1dc59c

**Comment by dvarubla** [comment]
@einhander не могу воспроизвести, хотя ввёл точно такую же команду из директории latex-g7-32. И лог у вас очень странный — почему-то каталог _minted-rpz создаётся в tex, хотя должен в mybuilddir (у меня в логе, например, ./_minted-rpz/bw.pygstyle). Может быть, какая-то ошибка с правами доступа? И можно скинуть ещё то, что выводит скрипт (`/build.sh -bd mybuilddir > output.txt`) ?

**Comment by einhander** [comment]
>почему-то каталог _minted-rpz создаётся в tex.
Он там и был :EPIC FAIL. Убрал, все стало ОК.
Вывод: надо чистить локальную репу.
Можно закрывать.
