### ISSUE TITLE
Несколько полезных для печати вещей

### ISSUE THREAD

**Issue by ZyX-I** [latex-g7-32/latex-g7-32#71]
У меня в дипломе ещё есть полезный скрипт: автоматизированное разделение PDF’ки на две «только цветные страницы» и «только чёрно‐белые страницы» средствами ghostscript, конвертация pdf в pdf им же для исправления проблемы, описанной в https://github.com/latex-g7-32/latex-g7-32/issues/43#issuecomment-302815849. Нужно это включать в шаблон?

Уточнение, зачем нужно: на работе цветные принтеры отдельно и ими просят без нужды не пользоваться, большой офисный принтер чёрно‐белый и без конвертации не печатает (своими силами с флэшки, через компьютер отрабатывает нормально) русский текст в dot графах. Считаю такое довольно обычной ситуацией, да и при печати за деньги ч/б и цветное идёт по разным тарифам.

(Кстати, с тирэ никаких проблем у меня нигде не было ещё до волны исправлений тирэ.)

**Comment by einhander** [comment]
@ZyX-I Скрипт конечно, полезный, спора нет, а в некоторых ситуациях просто незаменимый (например как у вас), но мне хотелось бы сконцентрировать наши усилия на самом шаблоне РПЗ и стиле как его основе.
Мое мнение - выкладывайте скрипт отдельным репозиторием, дадим ссылку на этот скрипт в ридми, и опционально подключаем в сборке с cmake.
@dvarubla ваше мнение?

**Comment by ZyX-I** [comment]
@einhander Слишком мелко для отдельного проекта. И неудобно. Такое удобнее делать частью системы сборки: чтобы на выходе было сразу `rpz.pdf`, `rpz-print.pdf`, `rpz-print-bw.pdf` и `rpz-print-col.pdf`. Я собственно себе на «сайт» примерно в таком виде и загружал из автоматизированной системы сборки.

**Comment by dvarubla** [comment]
Согласен с @einhander . Это всё-таки не совсем относится к стилю, примеру отчёта и его сборке. К тому же, у кого-то диплом полностью чёрно-белый, кому-то не жалко денег печатать несколько раз цветное. Да и этот скрипт был бы полезен сам по себе.
@ZyX-I сделайте лучше опцию, если она включена, то вызывается ваш скрипт. Я бы тоже добавил такую опцию в .latexmkmodrc.

**Comment by einhander** [comment]
Скрипт добавлен, можно закрыть.
