### ISSUE TITLE
При использовании PT Astra и Times New Roman не отображаются некоторые символы

### ISSUE THREAD

**Issue by ZyX-I** [latex-g7-32/latex-g7-32#72]
Речь идёт о том, что для следующего патча:

```patch
diff -r ca8f88281d78 tex/50-research.tex
--- a/tex/50-research.tex	Fri Aug 11 21:31:10 2017 +0300
+++ b/tex/50-research.tex	Fri Aug 11 22:58:05 2017 +0300
@@ -1,6 +1,18 @@
 \chapter{Экспериментальный раздел}
 \label{cha:research}
 
+Альфа-частицы:
+%\alpha-частицы (text, backslash),
+\(\alpha\)-частицы (math, backslash),
+α-частицы (text, unicode),
+\(α\)-частицы (math, unicode).
+
+Цельсий:
+\textcelsius{} (text, backslash),
+\(\textcelsius{}\) (math, backslash),
+℃ (text, unicode),
+\(℃\) (math, unicode).
+
 В данном разделе проводятся вычислительные эксперименты.
 А на рис.~\ref{fig:spire01} показана схема мыслительного процесса автора...
 
```

с установленными PT Astra результат выходит таким:

![работает только α+math+backslash](http://img-fotki.yandex.ru/get/241830/9151298.7/0_c686b_28ea2711_orig.png)

А если ещё добавить

```patch
diff -r ca8f88281d78 tex/GostBase.clo
--- a/tex/GostBase.clo	Fri Aug 11 21:31:10 2017 +0300
+++ b/tex/GostBase.clo	Fri Aug 11 23:06:11 2017 +0300
@@ -3,11 +3,11 @@
 \newif\if@usebold      \@useboldfalse
 \newcommand\Gost@encoding{}
 \newcommand\Gost@LineSpread{1.3}
-\ifPDFTeX
+%\ifPDFTeX
   \newcommand\Gost@fonts{times}
-\else
-  \newcommand\Gost@fonts{astra}
-\fi
+%\else
+%  \newcommand\Gost@fonts{astra}
+%\fi
 
 \DeclareOption{a3paper}{\setlength\paperheight{420mm}\setlength\paperwidth{297mm}}
 \DeclareOption{a4paper}{\setlength\paperheight{297mm}\setlength\paperwidth{210mm}}
```

то будет уже лучше:

![работают α+math+backslash и α+text+unicode](http://img-fotki.yandex.ru/get/233354/9151298.7/0_c686c_ccd5fc88_orig.png)

а с cm

```patch
diff -r ca8f88281d78 tex/GostBase.clo
--- a/tex/GostBase.clo	Fri Aug 11 21:31:10 2017 +0300
+++ b/tex/GostBase.clo	Fri Aug 11 23:10:21 2017 +0300
@@ -3,11 +3,11 @@
 \newif\if@usebold      \@useboldfalse
 \newcommand\Gost@encoding{}
 \newcommand\Gost@LineSpread{1.3}
-\ifPDFTeX
-  \newcommand\Gost@fonts{times}
-\else
-  \newcommand\Gost@fonts{astra}
-\fi
+%\ifPDFTeX
+  \newcommand\Gost@fonts{cm}
+%\else
+%  \newcommand\Gost@fonts{astra}
+%\fi
 
 \DeclareOption{a3paper}{\setlength\paperheight{420mm}\setlength\paperwidth{297mm}}
 \DeclareOption{a4paper}{\setlength\paperheight{297mm}\setlength\paperwidth{210mm}}
```

 всё куда‐то поехало (не разбирался, что и куда, но после перехода astra→times я увидел всё то же, а с times→cm я увидел следующую страницу; вроде разница в размерах шрифтов не должна быть настолько большой), но всё работает отлично:

![всё показывается как надо, кроме α+math+unicode](http://img-fotki.yandex.ru/get/765674/9151298.7/0_c686d_e767dd05_orig.png)

Вопрос: можно ли как‐то исправить первые два случая? Особенно учитывая то, что ℃ не работает вообще ни с какими ГОСТовскими шрифтами?

**Comment by ZyX-I** [comment]
(Проверял сборку на CMake+xelatex, но без docker.)

**Comment by LSinev** [comment]
@ZyX-I Догадки есть, почему так получается?

**Comment by ZyX-I** [comment]
По text, … — просто нет глифов. В PT Astra нет ни альфы, ни ℃. В Times New Roman есть альфа, но нет Цельсия. Почему то работает, то не работает математика не знаю, там вроде как другие шрифты. По идее, для текста дело должно сводится к использованию fallback шрифта, того же cm. Fontconfig такое умеет, а вот \*LaTeX — не знаю.

**Comment by LSinev** [comment]
Если я вбиваю ваш тестовый код в другой проект-репозиторий (https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/Dissertation/part1.tex#L148) под Windows и компилирую `lualatex` или `xelatex` под свежеобновленным TeXLive 2017, то вижу результат как у вас на последнем скриншоте. Times New Roman отрабатывает.

Если в `lualatex` или `xelatex` не подключен пакет `unicode-math` или аналог, то математический шрифт на базе CMUnicode идёт. В противном случае можно подобрать всякие XITS|STIX, Asana Math и т. п. под математику.

**Comment by einhander** [comment]
@ZyX-I сходу нагуглилось - пакеты unicode-math, textcomp и gensymb частично решают эту проблему в мат режиме для градусов цельсия.
Для греческих символов в xelatex  не указан греческих шрифт.
Для tmr `\newfontfamily\greecfont{cmunrm.otf}` вполне работает.

**Comment by ZyX-I** [comment]
А я тут уже подумал, что простейшим способом будет добавить скрипт на perl, который поищет `/^Missing character: There is no (.) in font (.+?)!$/ms` в файле `rpz.log` и назначит каждому найденному такому символу другой шрифт.

Кстати, почему у меня там

```
Missing character: There is no ℃ in font Times New Roman/OT:script=latn;languag
e=DFLT;mapping=tex-text;mapping=tex-text;!
```

? Во‐первых, xelatex действительно настолько неадекватен, что вставляет новые строки для обеспечения 80‐колоночного ограничения вместо того, чтобы просто давать терминалу (или текстовому редактору) делать свою работу? Во‐вторых, почему в сообщении об ошибке написано `latn`, а не `latin`?

**Comment by LSinev** [comment]
`latn` это определенная фича шрифта.
Поинтересуйтесь выдачей скрипта/программы `otfinfo` на разных *.ttf|*.otf

**Comment by dvarubla** [comment]
У меня c Times альфа тоже отображается, похоже, действительно, зависит от версии. Вообще, если какого-то символа нет в шрифте,  всегда можно написать что-то вроде: 
```latex
\newfontfamily\tmr{Times New Roman}
\DeclareRobustCommand{\talpha}{\ifmmode\alpha\else{\tmr α}\fi}
\catcode`\α=\active
\letα\talpha
```
или с использованием пакета newunicodechar.
А знак градуса `\degree` можно получить, подключив gensymb и textcomp.

В любом случае, не вижу смысла как-либо менять код стиля, так как символов довольно много.

**Comment by einhander** [comment]
Это особенности использования шрифтов и xelatex, в стандартном `article` те же проблемы. Закрываем.
