### ISSUE TITLE
Точка после номера section/subsection в XeLaTeX

### ISSUE THREAD

**Issue by onmotion** [latex-g7-32/latex-g7-32#78]
XeLaTeX (в sharelatex) собирает проект и упорно ставит точку после номера раздела, в то время как в PdfLatex  все ок.

![](https://image.ibb.co/ji4pZn/2018_04_02_19_48_14.png)

Подскажите куда копать

**Comment by onmotion** [comment]
В общем разобрался, это ставит **polyglossia**, замена его на **babel** решает проблему.

**Comment by dvarubla** [comment]
@onmotion В ShareLaTeX сильно устаревшая версия стиля и я не знаю, кто отвечает за его поддержку там. Вообще можно решить проблему и [менее радикально](https://github.com/latex-g7-32/latex-g7-32/commit/d19e773a50d63ad7df903c13322686bff4205db9).
