### ISSUE TITLE
Без \appendix расчет приложений в реферате неправильный.

### ISSUE THREAD

**Issue by einhander** [latex-g7-32/latex-g7-32#94]
Без \appendix расчет приложений в реферате неправильный, т.к. сейчас реализовано через подсчет глав.

**Comment by dvarubla** [comment]
А почему это баг? Что-то не очень понял.

**Comment by einhander** [comment]
Используется счетчик глав, \appendix его сбрасывает, соответственно без сброса количество приложений будет равно числу глав.
Проверяется очень просто убрать \appendix.

**Comment by dvarubla** [comment]
Так а зачем убирать `\appendix`? С ним же всё нормально работает или что-то не так?

**Comment by einhander** [comment]
Без него не работает))), как бы \appendix все же необязательная часть.

**Comment by dvarubla** [comment]
А, понятно. Ещё, кстати, в реферате не все склонения для источников указаны. Например, если будет 21 источник.

**Comment by einhander** [comment]
Да, тоже заметил такое. На самом деле в ГОСТ не регулирует как должно быть написано, в примере в ГОСТ 12 рис.. 24 табл.. 64 источи., 56 прил.
Предлагаю так и сделать, убрать склонения.
