### ISSUE TITLE
В соответствии с новым ГОСТ заголовки теперь полужирные

### ISSUE THREAD

**Issue by einhander** [latex-g7-32/latex-g7-32#95]
> 6.2.3 Заголовки разделов и подразделов основной части отчета следует начинать с абзацного
отступа и размещать после порядкового номера, печатать с прописной буквы, полужирным шрифтом,
не подчеркивать, без точки в конце.

**Comment by dvarubla** [comment]
Ну это сделать, думаю, несложно. А опцию `bold`, тогда, наверно, можно убрать?

**Comment by einhander** [comment]
Да, думаю можно убрать.

**Comment by dvarubla** [comment]
Только не совсем ясно, нужно ли так же и структурные элементы отчёта полужирным. По-моему, нет, хотя сейчас они полужирные. Это относится и к пунктам с подпунктами, у которых вообще нет заголовков (6.2.3 в ГОСТ)
