### ISSUE TITLE
Съезжаетют цифры в оглавлении

### ISSUE THREAD

**Issue by einhander** [latex-g7-32/latex-g7-32#97]
Съезжаетют цифры в оглавлении, если заголовок состоит из более чем 1 строки.

![123](https://user-images.githubusercontent.com/5439042/43045732-f0f7f7cc-8dc6-11e8-8c6f-476b5573853a.png)

**Comment by dvarubla** [comment]
Методом проб и ошибок выяснил, что нужно убрать пробел после `\hspace{.5em}` в макросе `\@dottedtocline` в G2-105.sty.

**Comment by dvarubla** [comment]
Можно так же: убрать и `\hspace`, и `\@chapapp`, но вдруг кто-то захочет свои префиксы глав; можно убрать и весь `\@dottedtocline`, но тогда изменятся отступы и будут более редкие точки.

**Comment by einhander** [comment]
Пробел убрал. А `\@chapapp` убирать нельзя, через него делается префикс у приложений.
